Repository metal3-io/cluster-api-provider-baremetal, pull requests merged in 2019-10, with the labels that each got.

#110 Add OWNERS file.
  OWNERS
Labels: size/XS

#114 Add hack scripts to run tests in containers.
  hack/gofmt.sh
  hack/govet.sh
  hack/unit.sh
Labels: approved, lgtm, size/M

#116 Add hack/markdownlint.sh.
  hack/markdownlint.sh
Labels: approved, lgtm, size/S

#117 Fix broken deployment example and update kustomize
  README.md
  config/default/kustomization.yaml
  config/default/manager_credentials_patch.yaml
  config/manager/credentials.yaml
  config/manager/kustomization.yaml
  examples/cluster/cluster.yaml
  examples/generate.sh
  go.mod
  hack/checkin_account.py
  hack/checkout_account.py
  hack/e2e-aws-disallowed.txt
  hack/e2e-aws-janitor.sh
  hack/e2e-aws-resources-list.sh
  hack/ensure-kustomize.sh
  hack/gofmt.sh
  hack/govet.sh
  hack/kind/start_controllers.sh
  hack/markdownlint.sh
  hack/print-workspace-status.sh
  hack/shellcheck.sh
  hack/terraform-gcr-init/README.md
  hack/terraform-gcr-init/user_project.tf
  hack/terraform-gcr-init/variables.tf
  hack/unit.sh
Labels: approved, lgtm, ok-to-test, size/XL

#119 Create and use a unit test image.
  hack/Dockerfile.unit
  hack/unit.sh
  tools/install_kubebuilder.sh
Labels: approved, lgtm, size/M

#120 Make the unit test script work under prow.
  hack/unit.sh
Labels: approved, lgtm, size/XS

#121 hack/govet: Set XDG_CACHE_HOME
  hack/govet.sh
Labels: approved, lgtm, size/XS

#122 Remove .travis.yml
  .travis.yml
Labels: approved, lgtm, size/S

#123 hack/unit: Set a default value for ARTIFACTS
  hack/unit.sh
Labels: approved, lgtm, size/XS

#125 Fix go vet and go fmt paths
  Makefile
  controllers/baremetalcluster_controller.go
  hack/Dockerfile.unit
  hack/gofmt.sh
  hack/govet.sh
  hack/unit.sh
Labels: approved, size/M

#128 [v1alpha2] Change capbm-unit image to use golang image
  hack/Dockerfile.unit
  hack/unit.sh
Labels: approved, lgtm, size/S

#129 Modify unit test image in v1alpha2 to avoid path collision in prow
  hack/Dockerfile.unit
  hack/unit.sh
Labels: approved, lgtm, size/XS

#130 [v1alpha2] Fix paths issue to run unit tests in v1alpha2 capbm-unit image
  Makefile
  hack/Dockerfile.unit
  hack/unit.sh
Labels: approved, lgtm, size/S

#131 [v1alpha2] Remove v1alpha2 unit test hack and change tmp dir
  hack/Dockerfile.unit
  hack/unit.sh
Labels: approved, lgtm, size/S

#118 [V1alpha2] Refactor the Makefile targets
  Makefile
  README.md
Labels: approved, lgtm, size/M

#134 V1alpha2 Use CAPI release-0.2 branch to avoid v1alpha3 issues
  Makefile
  examples/generate.sh
  hack/tools/install_kustomize.sh
Labels: approved, lgtm, size/S

#135 [v1alpha2] Apply RBAC when running make install
  Makefile
Labels: approved, lgtm, size/XS

#124 [v1alpha2] Fix deletion issue and add userdata secret creation for bmh
  baremetal/machine_manager.go
  config/rbac/role.yaml
  controllers/baremetalmachine_controller.go
Labels: approved, lgtm, size/L

#136 [v1alpha2] use controller-runtime logger and fix lint errors
  baremetal/cluster_manager.go
  baremetal/machine_manager.go
  baremetal/manager_factory.go
  controllers/baremetalcluster_controller.go
  controllers/baremetalmachine_controller.go
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#138 Remove rbac kustomization in install target
  Makefile
Labels: approved, lgtm, size/XS

#137 Add VIP in Baremetal Cluster
  api/v1alpha2/baremetalcluster_types.go
  baremetal/cluster_manager.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalclusters.yaml
  examples/cluster/cluster.yaml
Labels: approved, lgtm, size/M

#139 bug fix to prevent accessing Name on empty host
  baremetal/machine_manager.go
Labels: approved, lgtm, size/XS

#141 [v1alpha2] Use quay.io v1alpha2 image
  Makefile
  config/default/manager_image_patch.yaml
Labels: approved, lgtm, size/S

#140 [v1alpha2] Add namespace in providerID for unique naming
  baremetal/machine_manager.go
Labels: approved, lgtm, size/XS

#142 [v1alpha2] Modify image name for capbm for quay.io
  Makefile
  config/default/manager_image_patch.yaml
Labels: approved, lgtm, size/XS

#144 Adds leaderelectionID
  main.go
Labels: approved, lgtm, size/XS

#143 Added Test for BMHcluster
  controllers/baremetalcluster_controller_test.go
Labels: approved, lgtm, ok-to-test, size/M

#147 Add error fields for cluster and refactor machine status
  api/v1alpha2/baremetalcluster_types.go
  api/v1alpha2/baremetalcluster_types_test.go
  api/v1alpha2/baremetalmachine_types.go
  api/v1alpha2/baremetalmachine_types_test.go
  api/v1alpha2/zz_generated.deepcopy.go
  baremetal/cluster_manager.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalmachinetemplates.yaml
  controllers/baremetalcluster_controller.go
Labels: approved, lgtm, size/XL

#148 Remove unneeded CAPD functions
  baremetal/cluster_manager.go
  baremetal/machine_manager.go
  controllers/baremetalmachine_controller.go
Labels: approved, lgtm, size/M

#149 Add BareMetalCluster tests
  controllers/baremetalcluster_controller_test.go
  controllers/baremetalmachine_controller_test.go
  controllers/suite_test.go
Labels: approved, lgtm, ok-to-test, size/L

#151 Add BareMetalMachine Controller tests
  controllers/baremetalcluster_controller_test.go
  controllers/baremetalmachine_controller_test.go
  controllers/suite_test.go
Labels: approved, lgtm, size/XL
