Repository metal3-io/cluster-api-provider-baremetal, pull requests merged in 2019-11, with the labels that each got.

#154 Remove all references to keleustes repos from go.mod
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#153 [V1alpha2] Modify baremetalmachine workflow
  Makefile
  baremetal/machine_manager.go
  controllers/baremetalmachine_controller.go
  hack/gofmt.sh
  hack/govet.sh
  hack/markdownlint.sh
  hack/shellcheck.sh
  hack/unit.sh
Labels: approved, lgtm, size/L

#156 Harmonize Error and log messages
  controllers/baremetalmachine_controller.go
Labels: approved, lgtm, needs-ok-to-test, size/S

#159 Expand code coverage on baremetal machine controller
  baremetal/machine_manager.go
  controllers/baremetalcluster_controller_test.go
  controllers/baremetalmachine_controller.go
  controllers/baremetalmachine_controller_test.go
  controllers/suite_test.go
Labels: approved, lgtm, size/XXL

#158 Refactor unit tests for controller folder
  controllers/baremetalcluster_controller_test.go
  controllers/baremetalmachine_controller_test.go
  controllers/suite_test.go
Labels: approved, size/XXL

#155 CAPBM machine manager updates
  Makefile
  baremetal/machine_manager.go
  go.mod
Labels: approved, lgtm, size/L

#160 various minor fixes
  baremetal/machine_manager.go
  controllers/baremetalmachine_controller.go
  controllers/baremetalmachine_controller_test.go
  examples/metal3crds/metal3.io_baremetalhosts.yaml
  examples/metal3plane/hosts.yaml
  go.mod
Labels: approved, lgtm, size/XL

#161 V1alpha2 fix deletion workflow for cluster
  controllers/baremetalcluster_controller.go
  controllers/baremetalcluster_controller_test.go
  controllers/baremetalmachine_controller_test.go
Labels: approved, lgtm, size/L

#162 fix GetProviderID function
  baremetal/machine_manager.go
Labels: approved, lgtm, size/XS

#157 CAPBM machine mgr unit test
  baremetal/machine_manager_test.go
Labels: approved, lgtm, size/XXL

#164 Use bmh node UID for providerID instead of ironic UID
  baremetal/machine_manager.go
Labels: approved, lgtm, size/XS

#163 CAPBM machine_manager_test.go.old removed
  baremetal/machine_manager_test.go.old
Labels: approved, lgtm, size/XXL

#167 Add new error type APIEndPointError
  api/v1alpha2/baremetalcluster_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  baremetal/cluster_manager.go
  go.mod
Labels: approved, lgtm, size/M

#169 Add assertions to BM cluster controller test
  controllers/baremetalcluster_controller_test.go
Labels: approved, lgtm, size/S

#165 CAPBM: migrate consumerRef to BareMetalMachine
  baremetal/machine_manager.go
  baremetal/machine_manager_test.go
  controllers/baremetalmachine_controller.go
  controllers/baremetalmachine_controller_test.go
Labels: approved, lgtm, size/M

#172 Set erroreason & errormsg in BMCluster & BMMachine
  controllers/baremetalcluster_controller.go
  controllers/baremetalcluster_controller_test.go
  controllers/baremetalmachine_controller.go
Labels: approved, lgtm, size/L

#166 Remove setting error status on non-existing BMMachine
  controllers/baremetalmachine_controller.go
Labels: approved, lgtm, size/XS

#176 Fix assertion and comments
  controllers/baremetalcluster_controller.go
  controllers/baremetalcluster_controller_test.go
  controllers/baremetalmachine_controller.go
Labels: approved, lgtm, size/XS

#177 Parameterize setting error reason on Machine and Cluster
  baremetal/cluster_manager.go
  baremetal/machine_manager.go
Labels: approved, lgtm, size/S

#175 Sync and verify error status and message on BMMachine object
  baremetal/cluster_manager.go
  baremetal/machine_manager.go
  controllers/baremetalcluster_controller.go
  controllers/baremetalmachine_controller.go
  controllers/baremetalmachine_controller_test.go
Labels: approved, lgtm, size/L

#180 Rename cluster and machine manager files to reflect resources they ma…
  baremetal/baremetalcluster_manager.go
  baremetal/baremetalmachine_manager.go
  baremetal/baremetalmachine_manager_test.go
Labels: approved, lgtm, size/XS

#178 Update documentation
  README.md
  docs/api.md
  docs/deployment_workflow.md
  docs/dev-setup.md
  docs/dev/minikube.md
  docs/dev/openshift.md
  docs/dev/setup.md
Labels: approved, lgtm, size/XL

#181 Add shortNames for baremetalCluster and baremetalMachine
  api/v1alpha2/baremetalcluster_types.go
  api/v1alpha2/baremetalmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalmachines.yaml
Labels: approved, lgtm, size/S

#174 Improve assertions in BM Machine Contoller test
  controllers/baremetalcluster_controller_test.go
  controllers/baremetalmachine_controller_test.go
  controllers/suite_test.go
  go.sum
Labels: approved, lgtm, size/L

#171 Set node providerID on target cluster
  api/v1alpha2/baremetalcluster_types.go
  baremetal/baremetalmachine_manager.go
  baremetal/baremetalmachine_manager_test.go
  baremetal/remote/remote.go
  baremetal/remote/remote_test.go
  controllers/baremetalcluster_controller_test.go
  controllers/baremetalmachine_controller.go
  controllers/baremetalmachine_controller_test.go
  controllers/suite_test.go
  go.mod
  main.go
Labels: approved, lgtm, size/XXL

#173 CAPBM: cluster manager unit tests
  Makefile
  baremetal/cluster_manager_test.go
Labels: approved, lgtm, size/L

#183 Extent kubectl printout for baremetalcluster and baremetalmachine
  api/v1alpha2/baremetalcluster_types.go
  api/v1alpha2/baremetalmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalmachines.yaml
Labels: approved, lgtm, ok-to-test, size/S

#184 CAPBM: file naming alignment
  baremetal/baremetalcluster_manager_test.go
Labels: approved, lgtm, size/XS

#186 [V1alpha2] Adding unit tests with mocks for baremetalcluster controller
  Makefile
  baremetal/baremetalcluster_manager.go
  baremetal/baremetalcluster_manager_test.go
  baremetal/baremetalmachine_manager.go
  baremetal/baremetalmachine_manager_test.go
  baremetal/manager_factory.go
  baremetal/mock_baremetal/mock_baremetalcluster_manager.go
  baremetal/mock_baremetal/mock_manager_factory.go
  baremetal/suite_test.go
  controllers/baremetalcluster_controller.go
  controllers/baremetalcluster_controller_integration_test.go
  controllers/baremetalcluster_controller_test.go
  controllers/baremetalmachine_controller.go
  go.mod
  go.sum
Labels: approved, lgtm, size/XXL

#170 CAPBM increased coverage for machine manager unit test
  baremetal/baremetalmachine_manager_test.go
Labels: approved, lgtm, size/XL

#191 Changed error setting function signature and reduced verbosity of err…
  baremetal/baremetalcluster_manager.go
  baremetal/baremetalmachine_manager.go
  controllers/baremetalmachine_controller.go
Labels: approved, lgtm, size/S
