Repository metal3-io/cluster-api-provider-baremetal, pull requests merged in 2019-12, with the labels that each got.

#193 Update comments to reflect current changes.
  Makefile
  api/v1alpha2/baremetalmachine_types.go
  baremetal/baremetalcluster_manager.go
Labels: approved, lgtm, size/XS

#187 Refactor baremetal machine controller and manager code
  Makefile
  baremetal/baremetalcluster_manager_test.go
  baremetal/baremetalmachine_manager.go
  baremetal/baremetalmachine_manager_test.go
  baremetal/manager_factory_test.go
  baremetal/mock_baremetal/mock_baremetalmachine_manager.go
  baremetal/requeue_error_test.go
  baremetal/suite_test.go
  controllers/baremetalcluster_controller.go
  controllers/baremetalcluster_controller_test.go
  controllers/baremetalmachine_controller.go
  controllers/baremetalmachine_controller_integration_test.go
  controllers/baremetalmachine_controller_test.go
Labels: approved, lgtm, size/XXL

#195 fixes stuck deletion when host has no Status
  pkg/cloud/baremetal/actuators/machine/actuator.go
  pkg/cloud/baremetal/actuators/machine/actuator_test.go
Labels: approved, lgtm, size/M

#192 fix BMM flaky TestAssociate unit test
  baremetal/baremetalmachine_manager_test.go
Labels: approved, lgtm, size/M

#190 [v1alph2] Adding testing guidelines
  Makefile
  baremetal/mock_baremetal/mock_manager_factory.go
  baremetal/mocks/zz_generated.baremetalcluster_manager.go
  baremetal/mocks/zz_generated.baremetalmachine_manager.go
  controllers/baremetalcluster_controller_test.go
  controllers/baremetalmachine_controller_test.go
  docs/testing.md
Labels: approved, lgtm, size/L

#196 [V1alpha2] Handle properly bmh state none while deleting baremetal machine
  baremetal/baremetalmachine_manager.go
  baremetal/baremetalmachine_manager_test.go
Labels: approved, lgtm, size/S

#197 [V1alpha2] Refactor Baremetal cluster controller tests to use Ginkgo
  controllers/baremetalcluster_controller_test.go
Labels: approved, lgtm, size/L

#194 [V1alpha2] Refactor Baremetal machine controller tests to use Ginkgo
  controllers/baremetalmachine_controller_test.go
Labels: approved, lgtm, size/L

#199 Refactor manager factory unit tests
  baremetal/manager_factory_test.go
  baremetal/requeue_error_test.go
  baremetal/suite_test.go
Labels: approved, lgtm, size/L

#198 Refactor the error tests for the managers
  baremetal/requeue_error_test.go
  baremetal/suite_test.go
Labels: approved, size/M

#200 [V1alpha2] Refactoring baremetal cluster manager tests
  baremetal/baremetalcluster_manager_test.go
  controllers/baremetalcluster_controller_test.go
Labels: approved, lgtm, size/XL

#202 update gitignore
  .gitignore
Labels: approved, lgtm, size/XS

#203 Refactor baremetal machine manager tests
  baremetal/baremetalmachine_manager.go
  baremetal/baremetalmachine_manager_test.go
Labels: approved, lgtm, size/XXL

#204 Minor fixes for the tests
  baremetal/baremetalcluster_manager_test.go
  baremetal/baremetalmachine_manager_test.go
  controllers/baremetalcluster_controller_integration_test.go
  controllers/baremetalmachine_controller_integration_test.go
  controllers/baremetalmachine_controller_test.go
  controllers/suite_test.go
Labels: approved, lgtm, size/XL

#207 Change image tag to master
  config/default/manager_image_patch.yaml
  hack/unit.sh
Labels: approved, lgtm, size/XS

#206 Fix image version for deployment
  config/default/manager_image_patch.yaml
  hack/unit.sh
Labels: approved, lgtm, size/XS

#208 Set instance-state and instance-type.
  pkg/cloud/baremetal/actuators/machine/actuator.go
  pkg/cloud/baremetal/actuators/machine/actuator_test.go
Labels: approved, lgtm, size/M
