Repository metal3-io/cluster-api-provider-baremetal, pull requests merged in 2020-02, with the labels that each got.

#229 🐛 Fix manager image in release 0.2 branch
  config/default/manager_image_patch.yaml
Labels: approved, lgtm, size/XS

#233 ✨ Do not require generate-examples for Makefile targets
  Makefile
  config/default/manager_image_patch.yaml
Labels: approved, lgtm, size/XS

#235 🐛 Fix secret handling for baremetalmachine
  baremetal/baremetalmachine_manager.go
  baremetal/baremetalmachine_manager_test.go
Labels: approved, lgtm, size/L

#236 🏃 Remove unneeded clusterName from external object CRDs
  api/v1alpha3/baremetalcluster_types.go
  api/v1alpha3/baremetalmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalmachinetemplates.yaml
  examples/cluster/cluster.yaml
  examples/controlplane/controlplane.yaml
  examples/machinedeployment/machinedeployment.yaml
Labels: approved, lgtm, size/M

#237 🐛 Fix base64 decoding for UserData secret
  baremetal/baremetalmachine_manager.go
  baremetal/baremetalmachine_manager_test.go
Labels: approved, lgtm, size/S

#232 📖 Add release notes tool from Cluster API project
  Makefile
  hack/tools/release/notes.go
  hack/tools/tools.go
Labels: approved, lgtm, size/L

#234 📖 Add release notes tool from Cluster API project
  Makefile
  docs/api.md
  hack/tools/release/notes.go
  hack/tools/tools.go
Labels: approved, lgtm, size/L

#238 :sparkles: Add clusterLabel in BMH and BMC secret + tests
  baremetal/baremetalmachine_manager.go
  baremetal/baremetalmachine_manager_test.go
Labels: approved, lgtm, size/L

#239 :Bug: Fix clusterLabel deletion
  baremetal/baremetalmachine_manager.go
  baremetal/baremetalmachine_manager_test.go
Labels: approved, lgtm, size/M

#244 :Sparkles: Check Cluster.Spec.Pause and Pause Annotation in BMC & BMM reconcile
  controllers/baremetalcluster_controller.go
  controllers/baremetalcluster_controller_integration_test.go
  controllers/baremetalmachine_controller.go
  controllers/baremetalmachine_controller_integration_test.go
  controllers/baremetalmachine_controller_test.go
  controllers/suite_test.go
Labels: approved, lgtm, size/L

#243 🏃 Change manager image to master from v1alpha3
  config/default/manager_image_patch.yaml
Labels: approved, lgtm, size/XS

#246 ⚠️ Change package path and mocks path
  Makefile
  baremetal/baremetalcluster_manager.go
  baremetal/baremetalcluster_manager_test.go
  baremetal/baremetalmachine_manager.go
  baremetal/baremetalmachine_manager_test.go
  baremetal/manager_factory.go
  baremetal/manager_factory_test.go
  baremetal/mocks/zz_generated.baremetalcluster_manager.go
  baremetal/mocks/zz_generated.baremetalmachine_manager.go
  baremetal/suite_test.go
  controllers/baremetalcluster_controller.go
  controllers/baremetalcluster_controller_integration_test.go
  controllers/baremetalcluster_controller_test.go
  controllers/baremetalmachine_controller.go
  controllers/baremetalmachine_controller_integration_test.go
  controllers/baremetalmachine_controller_test.go
  controllers/suite_test.go
  go.mod
  main.go
Labels: approved, lgtm, size/M

#245 ⚠️ Change package path
  baremetal/baremetalcluster_manager.go
  baremetal/baremetalcluster_manager_test.go
  baremetal/baremetalmachine_manager.go
  baremetal/baremetalmachine_manager_test.go
  baremetal/manager_factory.go
  baremetal/manager_factory_test.go
  baremetal/mocks/zz_generated.baremetalmachine_manager.go
  baremetal/suite_test.go
  controllers/baremetalcluster_controller.go
  controllers/baremetalcluster_controller_integration_test.go
  controllers/baremetalcluster_controller_test.go
  controllers/baremetalmachine_controller.go
  controllers/baremetalmachine_controller_integration_test.go
  controllers/baremetalmachine_controller_test.go
  controllers/suite_test.go
  go.mod
  main.go
Labels: approved, lgtm, size/M

#247 📖 Change CI badges to v1alpha3
  README.md
Labels: approved, lgtm, size/XS

#248 🏃 bump image to v0.2.1
  config/default/manager_image_patch.yaml
Labels: approved, lgtm, size/XS

#253 🏃 Update go version to 1.13 for unit test docker image
  hack/Dockerfile.unit
  hack/govet.sh
Labels: approved, lgtm, size/XS

#254 🏃 Add Github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  hack/markdownlint.sh
Labels: approved, lgtm, size/M

#255 🏃 Refactor logging for controllers
  controllers/baremetalcluster_controller.go
  controllers/baremetalmachine_controller.go
Labels: approved, lgtm, size/S

#258 ⚠️ Require Go 1.13, Update dependencies and add preserveUnknownFields=false
  .gitignore
  Dockerfile
  Makefile
  baremetal/baremetalmachine_manager.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalmachinetemplates.yaml
  config/default/manager_image_patch.yaml
  controllers/suite_test.go
  go.mod
  go.sum
  hack/gofmt.sh
  hack/govet.sh
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/XL

#261 ✨ Add namespace selection for CAPBM controller
  main.go
Labels: approved, lgtm, size/XS

#262 ✨ Add OwnerReference and Finalizer on created userdata secret
  baremetal/baremetalmachine_manager.go
  baremetal/baremetalmachine_manager_test.go
Labels: approved, lgtm, size/M

#260 ✨ Add getting-started.md, metadata.yaml and update generate.sh
  .gitignore
  Makefile
  docs/getting-started.md
  examples/generate.sh
  examples/provider-components/kustomization.yaml
  metadata.yaml
Labels: approved, lgtm, size/M

#263 ✨ Set ownerreference on BareMetalHost
  baremetal/baremetalmachine_manager.go
  baremetal/baremetalmachine_manager_test.go
Labels: approved, lgtm, size/L

#264 ✨ Modify the userdata secret creation logic
  baremetal/baremetalmachine_manager.go
  baremetal/baremetalmachine_manager_test.go
  go.mod
  go.sum
Labels: approved, lgtm, size/L
