Repository metal3-io/cluster-api-provider-baremetal, pull requests merged in 2020-03, with the labels that each got.

#268 ✨ Rename Provider from Baremetal to Metal3
  README.md
  VERSIONING.md
  baremetal/baremetalcluster_manager.go
  baremetal/baremetalmachine_manager.go
  baremetal/baremetalmachine_manager_test.go
  baremetal/manager_factory.go
  baremetal/manager_factory_test.go
  config/default/kustomization.yaml
  config/kustomization.yaml
  controllers/baremetalcluster_controller.go
  controllers/baremetalmachine_controller.go
  docs/api.md
  docs/deployment_workflow.md
  docs/dev-setup.md
  docs/getting-started.md
  docs/testing.md
  examples/provider-components/manager_tolerations_patch.yaml
  hack/kind/start_controllers.sh
  main.go
Labels: approved, lgtm, size/L

#270 🐛 Fix leader election configmap name
  main.go
Labels: approved, size/XS

#231 Quick start guide for CAPBM
  README.md
  docs/architecture.md
  docs/images/components.png
  docs/images/controllerssequencediagram.png
  docs/images/fields_mapping.png
Labels: approved, lgtm, size/L

#266 📖 Update the documentation for v1alpha3
  .mdlrc
  Makefile
  README.md
  docs/api.md
  docs/deployment_workflow.md
  docs/dev-setup.md
  docs/releasing.md
Labels: approved, lgtm, size/L

#215 Change Baremetal to Bare Metal
  README.md
Labels: approved, lgtm, size/XS

#271 ⚠️ Deprecate repository
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: approved, lgtm, size/M

#272 clean up readme before archiving
  .travis.yml
  README.md
Labels: approved, do-not-merge/hold, lgtm, size/M
