Repository metal3-io/cluster-api-provider-baremetal, pull requests merged in 2020-01, with the labels that each got.

#219 add E2E tests status for v1alpha2
  README.md
Labels: approved, lgtm, size/XS

#218 add E2E tests build status for v1alpha1
  README.md
Labels: approved, lgtm, size/XS

#227 📖 Add developer documentation regarding version and releases
  CONTRIBUTING.md
  VERSIONING.md
Labels: approved, lgtm, size/L

#230 Fixes wrong reference of md in api docs
  docs/api.md
Labels: approved, lgtm, ok-to-test, size/XS
